import type { Metadata } from 'next';
import { Geist, Geist_Mono, Space_Grotesk } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { NavBar } from '@/components/navbar';

const geistHeading = Geist({ subsets: ['latin'], variable: '--font-heading' });

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-sans',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        spaceGrotesk.variable,
        geistHeading.variable
      )}
    >
      <body className='min-h-full flex flex-col'>
        <main className='max-w-7xl mx-auto w-full px-4 md:px-6 lg:px-8'>
          <NavBar />

          {children}
        </main>
      </body>
    </html>
  );
}
